# Generated by Django 5.0.7 on 2026-09-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(choices=[('potato', 'Irish Potato'), ('bolt', 'Electrical Equipment'), ('soya', 'Soya Pieces / Thumba'), ('oil', 'Mafuta (Cooking Oil)'), ('fish', 'Bonya Small Fish'), ('basket', 'Many Others')], default='basket', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True, help_text="Short blurb shown in the 'Our Markets' section.")),
                ('image_url', models.URLField(blank=True, help_text='Photo shown on the homepage for this market.')),
                ('typical_transport_fee', models.DecimalField(decimal_places=2, default=0, help_text='Round-trip transport cost Hopcee usually pays to reach this market (MWK).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('bag_50kg', '50kg Bag'), ('bag_90kg', '90kg Bag'), ('piece', 'Piece'), ('litre', 'Litre'), ('pack', 'Pack'), ('box', 'Box'), ('bucket', 'Bucket')], default='kg', max_length=20)),
                ('ordering_price', models.DecimalField(decimal_places=2, help_text='The buying price at the market (MWK) per unit.', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.market')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
